import * as cheerio from "cheerio"
import { checkSeo } from "./checks/seo/index"
import { checkAccessibility } from "./checks/accessibility/index"
import { checkPerformance } from "./checks/performance/index"
import { checkGeo } from "./checks/geo/index"
import { checkAeo } from "./checks/aeo/index"
import { enrichWithAiFixes, type AiHandler, type GscContext } from "./ai-fixes"
import { getWeight } from "./relevance"
import { detectFramework } from "./framework"

// Public type surface — consumers import these without pulling the Node-
// only scanner module graph.
export type { RawIssue, ScanIssue, ScanResult } from "./types"
export type { AiHandler, GscContext } from "./ai-fixes"
export type { FrameworkHint } from "./framework"
export { classifyPage, extractDomain, homepageUrl, type PageType } from "./classify-page"
import type { RawIssue, ScanIssue, ScanResult } from "./types"

// Markdown renderer re-exported so consumers don't need a second import.
export { toMarkdown } from "./markdown"

const SEVERITY_RANK: Record<RawIssue["severity"], number> = {
  critical: 0,
  warning: 1,
  info: 2,
}

function sortByRelevance(issues: RawIssue[]): RawIssue[] {
  return [...issues].sort((a, b) => {
    const severityDiff = SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]
    if (severityDiff !== 0) return severityDiff
    return getWeight(b.id) - getWeight(a.id) // higher weight = shown first within tier
  })
}

export async function runScanner(
  url: string,
  options?: {
    /** Provide pre-fetched HTML to skip the internal fetch. Useful when the
     *  caller already has the page in memory (e.g. a crawler, a screenshot
     *  pipeline). */
    prefetchedHtml?: string
    /** Skip site-wide probes (robots.txt, sitemap, llms.txt, skills.md,
     *  feed). Multi-page scan rotations set this on every non-root URL so
     *  the same site-level finding doesn't duplicate across pages. */
    skipSiteWideChecks?: boolean
    /** Search Console context for this exact URL — when present, anchors
     *  the AI "why" sentences to real impressions + position. Accept a
     *  promise so callers can fetch GSC in parallel with the page. */
    gsc?: GscContext | null | Promise<GscContext | null>
    /** Optional AI handler. When provided, each critical/warning issue
     *  gets an agent-ready `fix` + `why` string generated by the model.
     *  Omit to get raw rule-based fix strings with zero network calls. */
    ai?: AiHandler | null
  },
): Promise<ScanResult> {
  const t0 = Date.now()
  const fetchPageOrPrefetched = options?.prefetchedHtml
    ? Promise.resolve({ html: options.prefetchedHtml } as FetchResult)
    : fetchPage(url)
  const [fetchResult, { issues: perfIssues, data: perfData }, geoIssues] = await Promise.all([
    fetchPageOrPrefetched
      .catch(err => { console.error(`[scanner] fetchPage FAILED (${Date.now() - t0}ms):`, err); throw err }),
    checkPerformance(url)
      .catch(err => { console.warn(`[scanner] checkPerformance FAILED (non-fatal):`, err); return { issues: [] as RawIssue[], data: {} as import("./checks/performance/index").PerformanceData } }),
    checkGeo(url, { skipSiteWideChecks: options?.skipSiteWideChecks })
      .catch(err => { console.warn(`[scanner] checkGeo FAILED (non-fatal):`, err); return [] as RawIssue[] }),
  ])

  const { html, incompleteCertChain } = fetchResult
  const $ = cheerio.load(html)
  const seoIssues = checkSeo($, url)
  const a11yIssues = checkAccessibility($)
  const aeoIssues = checkAeo($, url)

  // Surface incomplete cert chain as a real finding — this misconfiguration
  // is invisible to browsers and Googlebot but breaks curl, Node fetch, and
  // other simpler clients. Worth fixing.
  const sslIssues: RawIssue[] = incompleteCertChain
    ? [
        {
          id: "ssl-incomplete-chain",
          category: "seo",
          severity: "warning",
          title: "TLS chain is missing an intermediate certificate",
          description:
            "Your server isn't sending the full certificate chain. Modern browsers and Googlebot work around this by fetching the missing intermediate via AIA, but simpler HTTP clients (curl, Node fetch, older libraries) will fail with UNABLE_TO_VERIFY_LEAF_SIGNATURE. Some monitoring tools, integrations, and webhook receivers will treat your site as unreachable.",
          fix:
            "Configure your server to send the full chain (root → intermediate → leaf). " +
            "On nginx: concatenate your leaf cert with the CA's intermediate bundle into ssl_certificate. " +
            "On Cloudflare: this is handled automatically — make sure SSL/TLS mode is 'Full' or higher. " +
            "Verify with: openssl s_client -showcerts -servername yourdomain.com -connect yourdomain.com:443 — you should see at least 2 certs in the chain.",
        },
      ]
    : []

  const sorted = sortByRelevance([...seoIssues, ...a11yIssues, ...perfIssues, ...geoIssues, ...aeoIssues, ...sslIssues])
  const framework = detectFramework($, html)

  // Await the GSC promise (or resolved value) right before Haiku runs — the
  // fetch has been in flight alongside PSI + cheerio so this is usually ~0ms.
  const gscResolved = options?.gsc instanceof Promise ? await options.gsc : options?.gsc ?? null

  const context = {
    url,
    title: $("title").text().trim(),
    description: $('meta[name="description"]').attr("content")?.trim() ?? "",
    h1: $("h1").first().text().trim(),
    bodyPreview: $("body").text().replace(/\s+/g, " ").trim().slice(0, 500),
    framework,
    gsc: gscResolved,
  }

  const enriched = await enrichWithAiFixes(sorted, context, options?.ai ?? null)

  // Every issue is returned. `gated` on ScanIssue is kept for backwards
  // compatibility with existing consumers but is always false in OSS —
  // gating lives in the hosted service, not in the scanner.
  const result: ScanIssue[] = enriched.map((issue) => ({ ...issue, gated: false }))

  console.log(`[scanner] Scan complete: ${result.length} issues, perf=${perfData.score}, lcp=${perfData.lcp}ms (total ${Date.now() - t0}ms)`)
  return { issues: result, performanceScore: perfData.score, lcp: perfData.lcp, cls: perfData.cls, framework: framework.framework }
}

function getErrorChain(err: unknown): string {
  const parts: string[] = []
  let current: unknown = err
  while (current instanceof Error) {
    parts.push(current.message)
    current = (current as Error & { cause?: unknown }).cause
  }
  return parts.join(" → ")
}

function isSslError(err: unknown): boolean {
  const chain = getErrorChain(err)
  return /certificate|SSL|ISSUER_CERT|CERT_LOCALLY/i.test(chain)
}

/**
 * Detects the specific TLS error class where the server failed to send the
 * intermediate certificate in its chain. Browsers and Googlebot transparently
 * fetch the missing intermediate via AIA (Authority Information Access). Node
 * does not — it bails with one of these error codes/messages.
 *
 * Other SSL errors (expired cert, hostname mismatch, self-signed) are NOT
 * matched here and continue to fail loudly.
 */
function isIncompleteChainError(err: unknown): boolean {
  const chain = getErrorChain(err)
  return /UNABLE_TO_VERIFY_LEAF_SIGNATURE|UNABLE_TO_GET_ISSUER_CERT|unable to verify the first certificate|unable to get local issuer certificate/i.test(
    chain,
  )
}

const FETCH_HEADERS = {
  "User-Agent": "SEOLint/1.0 (+https://seolint.dev/bot)",
  "Accept": "text/html,application/xhtml+xml",
  "Accept-Language": "en-US,en;q=0.9",
}

// Browser-impersonation headers used as a fallback when a server rejects our
// transparent bot UA (typical Cloudflare / WAF / government-site response).
// We start polite — if that fails we come back looking like Chrome desktop.
const BROWSER_FETCH_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "Accept":
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
  "Accept-Language": "en-US,en;q=0.9",
  "Accept-Encoding": "gzip, deflate, br",
  "Upgrade-Insecure-Requests": "1",
  "Sec-Ch-Ua": '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": '"Windows"',
  "Sec-Fetch-Dest": "document",
  "Sec-Fetch-Mode": "navigate",
  "Sec-Fetch-Site": "none",
  "Sec-Fetch-User": "?1",
}

// Status codes where it's worth retrying with browser impersonation. Anything
// else (404, 500, etc.) is a real page problem and we surface it honestly.
const BOT_REJECT_STATUS = new Set([401, 403, 406, 429, 503])

interface FetchResult {
  html: string
  /** Set when the cert chain was incomplete and we had to bypass strict validation */
  incompleteCertChain?: boolean
}

async function fetchPage(url: string): Promise<FetchResult> {
  try {
    const html = await doFetch(url, { lenientSsl: false, impersonateBrowser: false })
    return { html }
  } catch (err) {
    // Special case: incomplete cert chain. Browsers and Googlebot reach the
    // site fine via AIA fetching — Node doesn't. Retry once with relaxed
    // validation and surface a warning so the customer knows their TLS config
    // is fragile (some HTTP clients will still fail).
    if (isIncompleteChainError(err)) {
      console.warn(
        `[fetchPage] Incomplete cert chain for ${url}, retrying with relaxed TLS validation`,
      )
      try {
        const html = await doFetch(url, { lenientSsl: true, impersonateBrowser: false })
        return { html, incompleteCertChain: true }
      } catch {
        // Retry also failed → fall through to the normal error handling below
      }
    }

    // Special case: bot-reject status codes. Some sites (Cloudflare / WAFs /
    // government portals) return 403/429/503 to our transparent SEOLint UA.
    // Retry once impersonating a Chrome desktop browser before giving up.
    if (isBotRejectStatus(err)) {
      console.warn(
        `[fetchPage] Bot-rejected (${getBotRejectStatus(err)}) for ${url}, retrying with browser impersonation`,
      )
      try {
        const html = await doFetch(url, { lenientSsl: false, impersonateBrowser: true })
        return { html }
      } catch (retryErr) {
        if (isBotRejectStatus(retryErr)) {
          throw new Error(
            `${url} blocks automated scanning (HTTP ${getBotRejectStatus(retryErr)}). The site is behind a WAF or anti-bot protection (Cloudflare, Akamai, or similar) that rejects non-browser clients.`,
          )
        }
        // Other error — reassign so the normal handler below runs on the retry error
        err = retryErr
      }
    }

    const chain = getErrorChain(err)

    if (err instanceof Error && (err.name === "TimeoutError" || chain.includes("abort"))) {
      throw new Error(`Timeout: ${url} took longer than 12 seconds to respond`)
    }
    if (chain.includes("ENOTFOUND") || chain.includes("getaddrinfo")) {
      throw new Error(`DNS error: ${url} could not be resolved. Check the domain exists.`)
    }
    if (chain.includes("ECONNREFUSED")) {
      throw new Error(`Connection refused: ${url} is not accepting connections`)
    }
    if (isSslError(err)) {
      throw new Error(
        `SSL error: ${url} has a certificate issue that prevents scanning. The site may have an invalid, expired, or misconfigured SSL certificate.`,
      )
    }
    if (chain.includes("UND_ERR_SOCKET") || chain.includes("other side closed")) {
      throw new Error(`Connection error: ${url} closed the connection unexpectedly. Try again.`)
    }
    throw new Error(`Failed to fetch ${url}: ${chain}`)
  }
}

/** Returns true if the error is a bot-reject HTTP status thrown by doFetch. */
function isBotRejectStatus(err: unknown): boolean {
  if (!(err instanceof Error)) return false
  const match = err.message.match(/^HTTP (\d+)/)
  if (!match) return false
  return BOT_REJECT_STATUS.has(Number(match[1]))
}

function getBotRejectStatus(err: unknown): number | null {
  if (!(err instanceof Error)) return null
  const match = err.message.match(/^HTTP (\d+)/)
  return match ? Number(match[1]) : null
}

async function doFetch(
  url: string,
  opts: { lenientSsl: boolean; impersonateBrowser: boolean },
): Promise<string> {
  // Lazy-load got so it only pays its startup cost when a scan actually runs.
  // We use plain `got` instead of `got-scraping` because got-scraping's
  // header-generator dependency loads .zip files via adm-zip at module init
  // time, and Turbopack rewrites __dirname so the files can't be found on
  // Vercel serverless (ADM-ZIP: Invalid filename).
  const { default: got } = await import("got")

  const headers = opts.impersonateBrowser
    ? { ...BROWSER_FETCH_HEADERS, Referer: "https://www.google.com/" }
    : FETCH_HEADERS

  const response = await got(url, {
    timeout: { request: 12_000 },
    followRedirect: true,
    https: {
      rejectUnauthorized: !opts.lenientSsl,
    },
    headers,
    throwHttpErrors: false, // we handle status codes below
  })

  if (response.statusCode >= 400) {
    // Tag 404 / 410 specifically. The runner catches this error string and
    // stamps scans.status = "not_found" + prunes the path from watched_paths
    // so the agent stops spending quota on dead pages.
    const isGone = response.statusCode === 404 || response.statusCode === 410
    throw new Error(
      `${isGone ? "PAGE_NOT_FOUND: " : ""}HTTP ${response.statusCode} ${response.statusMessage ?? ""} fetching ${url}`.trim(),
    )
  }
  const html = response.body ?? ""
  if (!html || html.length < 50) {
    throw new Error(`Empty or too-short response from ${url} (${html.length} bytes)`)
  }
  return html
}

